services:
  postgresService:
    image: postgres
    environment:
      - POSTGRES_DB=ludik_tasks_db
      - POSTGRES_USER=dex
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data