name: Deploy to Vercel and run migrations

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install pnpm global
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --production

      - name: exists secret
        run: echo $hola
        env: 
          hola: ${{secrets.JWT_SECRET}}

      # - name: Run migrations 
      #   env:
      #     NODE_ENV: production
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_USER: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_NAME: ${{ secrets.DB_NAME }}
      #   run: npm run migrations:run

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      


